In [4]:
import numpy as np
import pandas as pd

In [1]:
'abcde'.islower()

True

In [6]:
x = np.array(dir(np))

In [10]:
x[pd.Series(x).str.islower() == True]

array(['__all__', '__builtins__', '__cached__', '__config__',
       '__deprecated_attrs__', '__dir__', '__doc__',
       '__expired_functions__', '__file__', '__getattr__',
       '__git_version__', '__loader__', '__name__', '__package__',
       '__path__', '__spec__', '__version__', '_add_newdoc_ufunc',
       '_distributor_init', '_financial_names', '_globals', '_mat',
       '_pyinstaller_hooks_dir', '_pytesttester', '_version', 'abs',
       'absolute', 'add', 'add_docstring', 'add_newdoc',
       'add_newdoc_ufunc', 'all', 'allclose', 'alltrue', 'amax', 'amin',
       'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes',
       'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan',
       'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition',
       'argsort', 'argwhere', 'around', 'array', 'array2string',
       'array_equal', 'array_equiv', 'array_repr', 'array_split',
       'array_str', 'asanyarray', 'asarray', 'asarray_chkfinite',
       'ascontiguousar

In [14]:
x = 2
y =3

In [15]:
eval('x+y')

5

In [19]:
exec('np.add(x,y)')

In [20]:
np.subtract(x,y)

-1

In [21]:
## 지수족 2, e
## Log 2, e, 10
np.exp2(3)

8.0

In [24]:
np.log10(3)

0.47712125471966244

In [25]:
np.log(2)

0.6931471805599453

In [32]:
x = np.arange(1,6)

np.add.reduce(x)

15

In [33]:
np.multiply.reduce(x)

120

In [34]:
np.prod(x)

120

In [35]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [36]:
np.random.seed(100)

In [37]:
x = np.random.randint(1,10,size=(5,5))

In [40]:
np.array(x > 5, dtype='int')

array([[1, 1, 0, 1, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0]])

In [41]:
rng = np.random.RandomState(42)

x = rng.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [45]:
y = list(x)

In [48]:
[y[3], y[7], y[2]]

[71, 86, 14]

In [49]:
x[[3,7,2]]

array([71, 86, 14])

In [50]:
x = np.array([2,1,4,3,5])

In [54]:
y = list(x)
y.sort()
y

[1, 2, 3, 4, 5]

In [55]:
np.random.seed(100)

In [57]:
score = np.random.randint(50, 100, size=(100,4))

In [60]:
score[np.argsort(score[:,3])[::-1],:]

array([[86, 92, 63, 98],
       [64, 84, 99, 98],
       [87, 60, 61, 98],
       [73, 59, 98, 98],
       [98, 59, 99, 97],
       [56, 84, 82, 97],
       [58, 90, 63, 97],
       [98, 97, 89, 95],
       [71, 50, 59, 95],
       [95, 87, 75, 95],
       [55, 52, 50, 95],
       [90, 87, 91, 94],
       [74, 65, 86, 93],
       [67, 74, 73, 92],
       [73, 97, 53, 91],
       [73, 69, 60, 91],
       [68, 82, 88, 90],
       [72, 87, 50, 90],
       [94, 50, 59, 90],
       [64, 83, 70, 90],
       [76, 69, 54, 89],
       [58, 74, 53, 89],
       [92, 56, 87, 89],
       [95, 62, 83, 88],
       [67, 70, 89, 88],
       [99, 79, 64, 88],
       [61, 99, 74, 87],
       [71, 75, 56, 87],
       [69, 86, 92, 87],
       [53, 76, 99, 86],
       [89, 86, 85, 85],
       [98, 66, 99, 85],
       [69, 54, 54, 85],
       [91, 80, 69, 84],
       [92, 72, 50, 84],
       [80, 84, 52, 84],
       [95, 76, 79, 82],
       [51, 86, 83, 82],
       [84, 92, 70, 81],
       [95, 75, 98, 81],


In [61]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [62]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [63]:
x = pd.DataFrame(x)

In [65]:
score = pd.DataFrame(score)
score

0   1   2   3
0   58  74  53  89
1   73  65  98  60
2   80  84  52  84
3   64  84  99  98
4   74  65  86  93
..  ..  ..  ..  ..
95  61  99  74  87
96  67  70  89  88
97  87  74  69  77
98  71  50  59  95
99  51  86  83  82

[100 rows x 4 columns]

In [80]:
score.iloc[:, 0] ## series

0     58
1     73
2     80
3     64
4     74
      ..
95    61
96    67
97    87
98    71
99    51
Name: 0, Length: 100, dtype: int64

In [81]:
score.iloc[:, 0:1] ## dataframe

0
0   58
1   73
2   80
3   64
4   74
..  ..
95  61
96  67
97  87
98  71
99  51

[100 rows x 1 columns]

In [82]:
score.values ## numpy array

array([[58, 74, 53, 89],
       [73, 65, 98, 60],
       [80, 84, 52, 84],
       [64, 84, 99, 98],
       [74, 65, 86, 93],
       [66, 59, 79, 72],
       [52, 77, 94, 54],
       [81, 51, 63, 69],
       [86, 54, 77, 53],
       [57, 99, 97, 51],
       [64, 57, 66, 52],
       [91, 80, 69, 84],
       [77, 96, 99, 80],
       [98, 97, 89, 95],
       [88, 94, 68, 50],
       [84, 60, 67, 58],
       [63, 92, 80, 67],
       [54, 90, 77, 77],
       [69, 64, 50, 63],
       [62, 92, 53, 56],
       [53, 70, 65, 60],
       [73, 97, 53, 91],
       [98, 93, 86, 55],
       [57, 88, 72, 80],
       [84, 92, 70, 81],
       [95, 62, 83, 88],
       [92, 72, 50, 84],
       [69, 54, 54, 85],
       [73, 59, 98, 98],
       [71, 75, 56, 87],
       [88, 89, 93, 80],
       [80, 52, 74, 67],
       [95, 87, 75, 95],
       [85, 66, 62, 72],
       [68, 95, 94, 53],
       [78, 81, 70, 60],
       [58, 75, 58, 80],
       [62, 68, 79, 78],
       [94, 50, 59, 90],
       [78, 52, 66, 55],


In [83]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [90]:
np.newaxis is None

True

In [87]:
## nan은 상수 / not a number
## inf (무한대)

In [88]:
x = np.random.randn(10, 11)

In [93]:
x[np.newaxis, :, :, np.newaxis].shape

(1, 10, 11, 1)

In [94]:
# SMOTE
from sklearn.datasets import load_wine

In [149]:
wine_df = pd.DataFrame(load_wine()['data'])
wine_df.columns = load_wine()['feature_names']
wine_df['grade'] = load_wine()['target']
wine_df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  grade  
0                            3.92   1065.0      0  
1                            3.40   1050.0      0  
2                            3.17   1185.0      0  
3                            3.45   1480.0      0  
4                            2.93    735.0      0  
..                            ...      ...    ...  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2  

[178 rows x 14 columns]

In [150]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  grade

In [152]:
(len(wine_df) - wine_df.isna().sum()).reset_index()

index    0
0                        alcohol  178
1                     malic_acid  178
2                            ash  178
3              alcalinity_of_ash  178
4                      magnesium  178
5                  total_phenols  178
6                     flavanoids  178
7           nonflavanoid_phenols  178
8                proanthocyanins  178
9                color_intensity  178
10                           hue  178
11  od280/od315_of_diluted_wines  178
12                       proline  178
13                         grade  178

In [153]:
pd.concat([wine_df.isna().sum(), wine_df.dtypes], axis=1)

0        1
alcohol                       0  float64
malic_acid                    0  float64
ash                           0  float64
alcalinity_of_ash             0  float64
magnesium                     0  float64
total_phenols                 0  float64
flavanoids                    0  float64
nonflavanoid_phenols          0  float64
proanthocyanins               0  float64
color_intensity               0  float64
hue                           0  float64
od280/od315_of_diluted_wines  0  float64
proline                       0  float64
grade                         0    int64

In [107]:
## dropna

In [110]:
x = np.random.randint(1,11, size=(100,5))
x = x.astype('object')

In [112]:
for _ in range(20):
    row = np.random.randint(0,100,1)
    col = np.random.randint(0,5,1)
    x[row, col] = np.nan
# x

In [114]:
x = pd.DataFrame(x)

In [117]:
x[x.isna().sum(axis=1) > 0]

0    1    2   3    4
0     3    4    6   6  NaN
5     1    2  NaN   5    4
8     6  NaN   10   5    8
9     7    5    3   9  NaN
10  NaN    7    7   1  NaN
12    3    3  NaN   2    7
18    3  NaN    6   3    1
25    4    2  NaN   1    3
26  NaN   10  NaN   4   10
29    4   10    6   5  NaN
30  NaN    8   10   5    2
35    4    1  NaN   1    3
41    5  NaN    1   8    4
43    8  NaN    7   6   10
48   10  NaN    2   9    5
52    1  NaN    8   2    1
54    7  NaN    6   4    7
58    1    4    7  10  NaN
65    3    1    8   6  NaN
70    9  NaN    4  10    4
73    8  NaN    6  10    9
74   10    3  NaN   4    1
80    8  NaN    6   6   10
82    9  NaN   10  10   10
84   10    9  NaN   4   10
85    8    7    9   4  NaN
87  NaN    1  NaN   7    9
89  NaN    3    2   3    5
90  NaN  NaN    4   4  NaN
98    2    8  NaN   5    1
99  NaN    6    1   4    2

In [128]:
x.fillna(method='ffill')

0  1   2  3     4
0    3  4   6  6   NaN
1    8  8   8  8   8.0
2    9  7   1  2  10.0
3   10  7   8  3   3.0
4    5  2   2  1   6.0
..  .. ..  .. ..   ...
95   7  6   4  7   2.0
96   9  4   7  2   6.0
97   9  5  10  7   6.0
98   2  8  10  5   1.0
99   2  6   1  4   2.0

[100 rows x 5 columns]

In [129]:
x = np.random.randint(1,10,100)
pd.Series(x).describe()

count    100.000000
mean       5.120000
std        2.535725
min        1.000000
25%        3.000000
50%        5.000000
75%        7.000000
max        9.000000
dtype: float64

In [130]:
x = x.astype('str')

In [132]:
pd.Series(x).describe()

count     100
unique      9
top         2
freq       17
dtype: object

In [135]:
x = np.random.randint(50, 100, size=(100,4))
x = pd.DataFrame(x)
x.columns = ['col_'+ str(i+1) for i in range(4) ]
x['gender'] = np.random.choice(np.array(['f', 'm']), 100)

In [139]:
x.groupby('gender').mean()[['col_1','col_2']]

col_1      col_2
gender                      
f       71.781818  75.036364
m       73.711111  75.022222

In [148]:
x.groupby('gender').mean()[['col_1','col_2']].unstack()

       gender
col_1  f         71.781818
       m         73.711111
col_2  f         75.036364
       m         75.022222
dtype: float64

In [142]:
import seaborn as sns
planet = sns.load_dataset('planets')
titanic = sns.load_dataset('titanic') 

In [143]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [144]:
planet

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [146]:
planet.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0