In [8]:
import numpy as np

In [9]:
W = W = np.array([[10], [20], [30], [40], [50], [60]])
b = 10

In [10]:
X = np.random.randn(1000,6)
y = np.dot(X,W) + b

In [11]:
W_hat = np.random.randn(6,1)
b_hat = 0

In [7]:
y_hat = np.dot(X,W_hat) + b_hat

In [9]:
def cost(W_hat, b_hat):
    y_hat = np.dot(X,W_hat) + b_hat
    return np.mean((y_hat-y)**2)

In [10]:
def diff(f,W_hat, b_hat):
    h = 1e-4
    dW = np.zeros_like(W_hat)
    for i in range(W_hat.shape[0]):
        for j in range(W_hat.shape[1]):
            fx = f(W_hat, b_hat)            
            tmp = W_hat[i,j]
            W_hat[i,j] = tmp + h
            fxh = f(W_hat, b_hat)
            dW[i,j] = (fxh - fx)/h
            W_hat[i,j] = tmp
    fx = f(W_hat, b_hat)
    fxh = f(W_hat, b_hat+h)
    db = (fxh - fx)/h
    return dW, db

diff(cost, W_hat, b_hat)

(array([[ -15.29231999],
        [ -38.404723  ],
        [ -68.9202192 ],
        [ -80.76276989],
        [-102.88514364],
        [-120.64326591]]),
 -17.26994172713603)

In [16]:
# diff(cost, W_hat, b_hat)[0]

array([[-6.10734060e-08],
       [ 2.50154129e-08],
       [ 7.09510152e-07],
       [-6.20127454e-07],
       [-2.98607894e-07],
       [-5.27165915e-07]])

In [11]:
lr = 1e-3
for _ in range(10000):
    W_hat -= diff(cost, W_hat, b_hat)[0]*lr
    b_hat -= diff(cost, W_hat, b_hat)[1]*lr

In [12]:
print(W_hat)
print(b_hat)

[[ 9.99994817]
 [19.99995098]
 [29.99995571]
 [39.99995526]
 [49.99995012]
 [59.99995004]]
9.999950508626453


In [13]:
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
a= a.reshape(-1,3)

In [19]:
a.shape

(8, 3)

In [20]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [22]:
a = a.reshape(-1,1)

In [23]:
a.shape

(24, 1)